name: Merge
run-name: Merging ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}

on:
  pull_request_review:
    types:
    - submitted

permissions:
  contents: read

jobs:
  merge:
    if: github.event.review.state == 'approved'
        && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          version.txt
        sparse-checkout-cone-mode: false
    - name: Merge
      uses: lime-actions/merge@v1
      with:
        version-from: version-file
        version-source: version.txt
        merge-mode-other: rebase
        merge-mode-fallback: merge
    - name: Merge back
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"

        git fetch

        git checkout release-candidate
        git merge origin/${{ github.event.pull_request.base.ref }} -X ours
        git push

        git checkout dev
        git merge release-candidate -X ours
        git push
