name: Create PR
run-name: Creating PR from ${{ github.ref_name }}

on:
  push:

jobs:
  create-pr:
    if: github.ref_name != github.event.repository.default_branch
    runs-on: ubuntu-latest
    permissions:
       pull-requests: write
       contents: read
    steps:
    - name: Create PR from ${{ github.ref_name }}
      uses: lime-actions/pr-sync@v1
      with:
        version-from: version-file
        version-source: version.txt
